repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.13
    hooks:
      - id: ruff
        args: [ document-ia-api, --fix ]
        files: ^(document-ia-api|document-ia-infra|document-ia-worker)/src/.*.py$
      - id: ruff-format
        files: ^(document-ia-api|document-ia-infra|document-ia-worker)/src/.*.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-added-large-files
        exclude: ^document-ia-api/src/static/
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
        args: ["--config", ".gitleaks.toml"]

  # Hooks locaux pour gérer uv lock par sous-projet lorsque le pyproject.toml change
  - repo: local
    hooks:
      - id: uv-lock-schemas
        name: uv lock (schemas)
        language: system
        pass_filenames: false
        files: ^document-ia-schemas/pyproject.toml$
        entry: bash -c 'cd document-ia-schemas && uv lock'
      - id: uv-lock-infra
        name: uv lock (infra)
        language: system
        pass_filenames: false
        files: ^document-ia-infra/pyproject.toml$
        entry: bash -c 'cd document-ia-infra && uv lock'
      - id: uv-lock-auto-scaler
        name: uv lock (auto-scaler)
        language: system
        pass_filenames: false
        files: ^document-ia-auto-scaler/pyproject.toml$
        entry: bash -c 'cd document-ia-auto-scaler && uv lock'
      - id: uv-lock-api
        name: uv lock (api)
        language: system
        pass_filenames: false
        files: ^document-ia-api/pyproject.toml$
        entry: bash -c 'cd document-ia-api && uv lock'
      - id: uv-lock-worker
        name: uv lock (worker)
        language: system
        pass_filenames: false
        files: ^document-ia-worker/pyproject.toml$
        entry: bash -c 'cd document-ia-worker && uv lock'
      - id: uv-lock-evals
        name: uv lock (evals)
        language: system
        pass_filenames: false
        files: ^document-ia-evals/pyproject.toml$
        entry: bash -c 'cd document-ia-evals && uv lock'
