services:
  postgres:
    image: postgres:17-alpine
    container_name: document-ia-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - document-ia-network

  redis:
    image: redis:8-alpine
    container_name: document-ia-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - document-ia-network

volumes:
  postgres_data:
  redis_data:

networks:
  document-ia-network:
    driver: bridge
