"""Create event store table

Revision ID: 5876b08c4f42
Revises:
Create Date: 2025-09-03 17:25:22.205108

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5876b08c4f42"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_store",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique identifier for the event"
        ),
        sa.Column(
            "workflow_id",
            sa.String(length=255),
            nullable=False,
            comment="Workflow identifier",
        ),
        sa.Column(
            "execution_id",
            sa.String(length=255),
            nullable=False,
            comment="Execution instance identifier",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Event timestamp",
        ),
        sa.Column(
            "event_type",
            sa.String(length=100),
            nullable=False,
            comment="Type of event (e.g., WorkflowExecutionStarted)",
        ),
        sa.Column(
            "event",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Event payload as JSON",
        ),
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            comment="Event version for optimistic locking",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id", "execution_id", "event_type", "version"),
    )
    op.create_index(
        "idx_event_store_created_at", "event_store", ["created_at"], unique=False
    )
    op.create_index(
        "idx_event_store_execution_version",
        "event_store",
        ["execution_id", "version"],
        unique=False,
    )
    op.create_index(
        "idx_event_store_execution_workflow",
        "event_store",
        ["execution_id", "workflow_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_store_created_at"), "event_store", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_event_store_event_type"), "event_store", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_event_store_execution_id"),
        "event_store",
        ["execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_event_store_workflow_id"), "event_store", ["workflow_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_event_store_workflow_id"), table_name="event_store")
    op.drop_index(op.f("ix_event_store_execution_id"), table_name="event_store")
    op.drop_index(op.f("ix_event_store_event_type"), table_name="event_store")
    op.drop_index(op.f("ix_event_store_created_at"), table_name="event_store")
    op.drop_index("idx_event_store_execution_workflow", table_name="event_store")
    op.drop_index("idx_event_store_execution_version", table_name="event_store")
    op.drop_index("idx_event_store_created_at", table_name="event_store")
    op.drop_table("event_store")
    # ### end Alembic commands ###
